### ISSUE TITLE
cpufetch inside qemu VM with pentium CPU segfaults.

### ISSUE THREAD

**Issue by bernhardu** [Dr-Noob/cpufetch#131]
Hello, I was just trying to do some debugging of the Debian bugs also mentioned in # 128.

Lacking a current installation at the matching hardware I tried with my `AMD Ryzen 7` a virtual machine with `qemu-system-i386 -enable-kvm -cpu pentium ...`.

There I got this crash:
```cpp
# apt build-dep
# apt install cpufetch cpufetch-dbgsym gdb

$ mkdir /home/benutzer/source/cpufetch/orig -p
$ cd /home/benutzer/source/cpufetch/orig
$ apt source cpufetch

# lscpu
Architecture:            i586
  CPU op-mode(s):        32-bit
  Address sizes:         36 bits physical, 32 bits virtual
  Byte Order:            Little Endian
CPU(s):                  16
  On-line CPU(s) list:   0-15
Vendor ID:               AuthenticAMD
  BIOS Vendor ID:        QEMU
  Model name:            05/04
    BIOS Model name:     pc-i440fx-6.1
    CPU family:          5
    Model:               4
    Thread(s) per core:  1
    Core(s) per socket:  1
    Socket(s):           16
    Stepping:            3
    BogoMIPS:            5988.74
    Flags:               fpu vme de pse tsc msr cx8 apic mmx cpuid tsc_known_freq x2apic hypervisor vmmcall
Virtualization features: 
  Hypervisor vendor:     KVM
  Virtualization type:   full
Vulnerabilities:         
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Spec store bypass:     Vulnerable
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Full generic retpoline, STIBP disabled, RSB filling
  Srbds:                 Not affected
  Tsx async abort:       Not affected
# gdb -q --args cpufetch
Reading symbols from cpufetch...
Reading symbols from /usr/lib/debug/.build-id/46/9615f54c302dabf53d9bc8f99de23ed9b7fda3.debug...
(gdb) set width 0
(gdb) set pagination off
(gdb) directory /home/benutzer/source/cpufetch/orig/cpufetch-1.0+git20211101+a5b321a9668f
Source directories searched: /home/benutzer/source/cpufetch/orig/cpufetch-1.0+git20211101+a5b321a9668f:$cdir:$cwd
(gdb) run
Starting program: /usr/bin/cpufetch 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00406532 in get_cache_topology_amd (cpu=0x41a1c0, topo=0x41a2f0) at src/x86/cpuid.c:458
458         topo->cach->L1i->num_caches = topo->physical_cores;
(gdb) bt full
#0  0x00406532 in get_cache_topology_amd (cpu=0x41a1c0, topo=0x41a2f0) at src/x86/cpuid.c:458
No locals.
#1  0x00406847 in get_topology_info (cpu=0x41a1c0, cach=0x0) at src/x86/cpuid.c:574
        topo = 0x41a2f0
        eax = 0
        ebx = 0
        ecx = 0
        edx = 0
#2  0x004071ad in get_cpu_info () at src/x86/cpuid.c:390
        cpu = 0x41a1c0
        feat = 0x41a200
        ptr = <optimized out>
        eax = 1347
        ebx = 167774208
        ecx = 2149580800
        edx = 8389567
        name = "AuthenticAMD"
#3  0x00401385 in main (argc=1, argv=0xbffffde4) at src/common/main.c:129
        cpu = <optimized out>
(gdb) print topo
$1 = (struct topology *) 0x41a2f0
(gdb) print topo->cach
$2 = (struct cache *) 0x0
(gdb) print topo->physical_cores
$3 = 1
(gdb) display/i $pc
1: x/i $pc
=> 0x406532 <get_cache_topology_amd+290>:       mov    (%eax),%ecx
(gdb) print/x $eax
$4 = 0x0
(gdb) print cache_level
No symbol "cache_level" in current context.
(gdb) list
453           i++;
454         } while (cache_type > 0);
455       }
456       else {
457         printWarn("Can't read topology information from cpuid (needed extended level is 0x%.8X, max is 0x%.8X and topology_extensions=%s). Guessing cache topology", 0x8000001D, cpu->maxExtendedLevels, cpu->topology_extensions ? "true" : "false");
458         topo->cach->L1i->num_caches = topo->physical_cores;
459         topo->cach->L1d->num_caches = topo->physical_cores;
460
461         if(topo->cach->L3->exists) {
462           topo->cach->L2->num_caches = topo->physical_cores;
(gdb)
```

Which I could workaround by:
```diff
--- cpufetch-1.0+git20211101+a5b321a9668f.orig/src/x86/cpuid.c
+++ cpufetch-1.0+git20211101+a5b321a9668f/src/x86/cpuid.c
@@ -454,6 +454,10 @@ bool get_cache_topology_amd(struct cpuIn
     } while (cache_type > 0);
   }
   else {
+    if (!topo->cach) {
+        printWarn("topo->cach not valid");
+        return false;
+    }
     printWarn("Can't read topology information from cpuid (needed extended level is 0x%.8X, max is 0x%.8X and topology_extensions=%s). Guessing cache topology", 0x8000001D, cpu->maxExtendedLevels, cpu->topology_extensions ? "true" : "false");
     topo->cach->L1i->num_caches = topo->physical_cores;
     topo->cach->L1d->num_caches = topo->physical_cores;
```

With the above change applied I found cpufetch giving no output, maybe like in Debian bug 999591 from # 128.
This I assume is caused by `topo->cach` being NULL.
```cpp
(gdb) bt
#0  get_cpu_info () at src/x86/cpuid.c:393
#1  0x00401385 in main (argc=1, argv=0xbffffde4) at src/common/main.c:129
(gdb) list
388       cpu->freq = get_frequency_info(cpu);
389       cpu->cach = get_cache_info(cpu);
390       cpu->topo = get_topology_info(cpu, cpu->cach);
391       cpu->peak_performance = get_peak_performance(cpu, cpu->topo, get_freq(cpu->freq), accurate_pp());
392
393       if(cpu->cach == NULL || cpu->topo == NULL) {
394         return NULL;
395       }
396       return cpu;
397     }
(gdb) print cpu->cach
$3 = (struct cache *) 0x0
(gdb) print cpu->topo
$4 = (struct topology *) 0x41a2f0
```
And verbose shows this:
```
# cpufetch -v
[WARNING]: Can't read features information from cpuid (needed level is 0x00000007, max is 0x00000001)
[WARNING]: Can't read features information from cpuid (needed extended level is 0x80000001, max is 0x00000000)
[WARNING]: Can't read cpu name from cpuid (needed extended level is 0x80000004, max is 0x00000000)
[WARNING]: Can't read frequency information from cpuid (needed level is 0x00000016, max is 0x00000001). Using udev
[WARNING]: Could not open '/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq'
[WARNING]: Can't read cache information from cpuid (needed extended level is 0x8000001D, max is 0x00000000 and topology_extensions=false)
[WARNING]: Can't read cache information from cpuid using old method (needed extended level is 0x80000006, max is 0x00000000)
[WARNING]: Can't read topology information from cpuid (needed extended level is 0x80000008, max is 0x00000000)
[WARNING]: topo->cach not valid
```
This is with Debian package version `1.0+git20211101+a5b321a9668f-3` of cpufetch, which should match a5b321a966.

**Comment by Dr-Noob** [comment]
Thanks a lot for your report. I thought that bugs found in Debian were all fixed in the upstream version, but I was wrong.

This bug only occurs when cpufetch is executed in a "hostile" environment, like virtual machines, where the maximum level of cpuid is insanely low (in your case, it seems that the max level is 0x1!). This is obviously restricted by the hypervisor. And cpufetch will not print much information under these circumstances but it should, at least, don't crash and actually print something.

I've pushed a new commit to `bugfix2`. Could you give it a try and let me know if it works now? Thanks!

**Comment by bernhardu** [comment]
Thanks for taking care. I have checked `bugfix2` with current Debian testing/bookworm inside a `qemu -cpu pentium` VM.
![grafik](https://user-images.githubusercontent.com/10096970/144717287-043b9623-d5c3-4c3a-8ddb-a62f144946b7.png)
It works and I guess as expected as the bare metal below is a Ryzen cpu.

One small thing not strictly related first I got a `Makefile:45: Unsupported arch detected: i586. See https://github.com/Dr-Noob/cpufetch#1-support`.
Following enabled building inside that machine:
```diff
--- a/Makefile
+++ b/Makefile
@@ -12,7 +12,7 @@ COMMON_HDR = $(SRC_COMMON)ascii.h $(SRC_COMMON)cpu.h $(SRC_COMMON)udev.h $(SRC_C
 
 ifneq ($(OS),Windows_NT)
        arch := $(shell uname -m)
-       ifeq ($(arch), $(filter $(arch), x86_64 amd64 i686))
+       ifeq ($(arch), $(filter $(arch), x86_64 amd64 i686 i586))
                SRC_DIR=src/x86/
```

```
$ uname -a
Linux debian 5.15.0-2-686-pae #1 SMP Debian 5.15.5-1 (2021-11-26) i586 GNU/Linux
$ lscpu
Architecture:            i586
  CPU op-mode(s):        32-bit
  Address sizes:         36 bits physical, 32 bits virtual
  Byte Order:            Little Endian
CPU(s):                  16
  On-line CPU(s) list:   0-15
Vendor ID:               AuthenticAMD
...
```

**Comment by Dr-Noob** [comment]
Cool! I'll merge the changes into master, as it looks like the issue is fixed. I already added the `i586` and other archs to Makefile in master. 

Thanks for the help!
