### ISSUE TITLE
Crash on 24 core ARM

### ISSUE THREAD

**Issue by bbonev** [Dr-Noob/cpufetch#137]
```` c
(gdb) run
Starting program: /root/cpufetch/cpufetch 
malloc(): corrupted top size

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x0000fffff7e79ea0 in __GI_abort () at abort.c:79
#2  0x0000fffff7ec7280 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0xfffff7f8b010 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x0000fffff7ece7dc in malloc_printerr (str=str@entry=0xfffff7f87218 "malloc(): corrupted top size") at malloc.c:5347
#4  0x0000fffff7ed1c28 in _int_malloc (av=av@entry=0xfffff7fc6a98 <main_arena>, bytes=bytes@entry=4096) at malloc.c:4107
#5  0x0000fffff7ed2b28 in __GI___libc_malloc (bytes=4096) at malloc.c:3058
#6  0x0000aaaaaaaa770c in emalloc (size=4096) at src/common/global.c:94
#7  0x0000aaaaaaaa3050 in read_file (path=0xaaaaaaab5bd8 "/proc/cpuinfo", len=0xfffffffff9c0) at src/common/udev.c:58
#8  0x0000aaaaaaaaf9fc in get_midr_from_cpuinfo (core=1, success=0xfffffffffa3f) at src/arm/udev.c:40
#9  0x0000aaaaaaaa80a8 in get_cpu_info_linux (cpu=0xaaaaaaacb2d0) at src/arm/midr.c:199
#10 0x0000aaaaaaaa839c in get_cpu_info () at src/arm/midr.c:307
#11 0x0000aaaaaaaa20d8 in main (argc=1, argv=0xfffffffffc38) at src/common/main.c:129
(gdb) frame 7
#7  0x0000aaaaaaaa3050 in read_file (path=0xaaaaaaab5bd8 "/proc/cpuinfo", len=0xfffffffff9c0) at src/common/udev.c:58
58	  char* buf = emalloc(sizeof(char)*DEFAULT_FILE_SIZE);
(gdb) 
````

PS. I remember that you do not like pull requests, here is the output after fixing the problem:
![image](https://user-images.githubusercontent.com/658788/152664274-cfd48a7e-5cf5-4bd5-b300-2cf97ca9e3f0.png)

**Comment by Dr-Noob** [comment]
Can you paste the output of `lscpu` or provide details about the CPU?

**Comment by bbonev** [comment]
````
# lscpu
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          24
On-line CPU(s) list:             0-23
Thread(s) per core:              1
Core(s) per socket:              24
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       ARM
Model:                           4
Model name:                      Cortex-A53
Stepping:                        r0p4
BogoMIPS:                        200.00
L1d cache:                       768 KiB
L1i cache:                       768 KiB
L2 cache:                        3 MiB
L3 cache:                        4 MiB
NUMA node0 CPU(s):               0-23
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
````

This is a socionext synquacer board.
I can run any commands and provide the result...

**Comment by Dr-Noob** [comment]
I see, thanks a lot for the notice. The `read_file` function was clearly not very well implemented :sweat_smile:.

I have uploaded a fix, it should work now for a `/proc/cpuinfo` of any size. I would appreciate it if you confirm that it works, and also if you could paste your `/proc/cpuinfo` (or maybe upload it somewhere in case it is very big, as it seems that it is).

**Comment by bbonev** [comment]
http://paste.debian.net/1230310/

**Comment by Dr-Noob** [comment]
As always, great suggestions, bbonev. I totally agree with the `memset` thing. And for the buffer growth, I made it linear with fixed increments. As you said, this will be unnoticeable.

I asked for the `/proc/cpuinfo` because I was hoping to find something there to detect the SoC, but unfortunately, there's nothing useful. Regarding the frequency, I guess that there are no `/sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_max_freq` files, so there is nothing to do in this case either.

I'm closing the issue, but feel free to continue the discussion if you wish. I always enjoy discussing the project, especially when there is an opportunity to improve it, as often is the case when you participate.
